### ISSUE TITLE
gunicorn: not found

### ISSUE THREAD

**Issue by peterfox1** [AWildLeon/Glance-iCal-Events#2]
Hi, nice work with this project, it will be great. I tried to run the docker container (:main) but it stops with this error:

`/bin/sh: [gunicorn,: not found`

Compose:
```yml
  glance_ical_api:
    image: ghcr.io/awildleon/glance-ical-events:main
    container_name: glance_ical_api
    restart: unless-stopped
```
Log:
```
/bin/sh: [gunicorn,: not found
```

Not sure if I was missing something, or perhaps there was something up with the `:main` tag currently.
